// type 설정
export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const SET_USER_INFO = 'SET_USER_INFO';
export const DELETE_USER_INFO = 'DELETE_USER_INFO';
export const SET_BOARDLIST = 'SET_BOARDLIST';
export const ADD_BOARDITEM = 'ADD_BOARDITEM';
export const DELETE_BOARDITEM = 'DELETE_BOARDITEM';
export const SET_PAGINATION = 'SET_PAGINATION';
